# # Taps

tap "kgarner7/feishin"

# # Brews

brew "bat"
brew "bitwise"
brew "cmake"
brew "coreutils" # GNU File, Shell, and Text utilities
brew "difftastic"
brew "direnv"
brew "fish"
brew "modules"
brew "wader/tap/fq"
brew "fzf"
brew "gdb"
brew "grep"
brew "gnupg"
brew "htop"
brew "hunspell"
brew "imagemagick"
brew "llvm" # lldb-dap; keg-only, resolved by ~/.local/bin/lldb-dap
brew "navidrome"
brew "neovim"
brew "pass"
brew "pkg-config"
brew "qemu"
brew "ranger"
brew "ripgrep"
# brew "starship" # / pure
brew "stow"
brew "tmux"
brew "zoxide"

# tree-sitter
brew "tree-sitter"
brew "tree-sitter-cli"

# linting
brew "gersemi" # cmake
brew "prettier"
brew "shfmt"
brew "texlab" # TeX
brew "typos-cli" # typos

# git
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "git-lfs"
brew "gitui"

# lisp
brew "minimal-racket"

# lua
brew "luarocks"

# markdown
brew "comrak" # GFM(arkdown)

#python
brew "python"
brew "ruff"
brew "ty"
brew "uv"
brew "yapf"

# rust
brew "rust-analyzer"

# sh
brew "bash-language-server" # mostly works for zsh

# toml
brew "taplo"

# tools
brew "z3"

# libs
brew "openblas"

# # Casks

cask  "appcleaner"
cask  "calibre"
# cask  "feishin"
cask  "hammerspoon"
cask  "iina"
cask  "keepassxc"
cask  "keka"
cask  "raycast"
cask  "rectangle"
cask  "skim"
cask  "vlc"

# # Fonts
cask "font-m+-nerd-font"
cask "font-source-code-pro"
