brewfile_dir = __dir__
core_brewfile = [
  File.join(brewfile_dir, "Brewfile.core"),
  File.expand_path("../../../common/.config/brew/Brewfile.core", brewfile_dir),
].find { |path| File.file?(path) }
common_optional_brewfile = [
  File.join(brewfile_dir, "Brewfile.optional.common"),
  File.expand_path("../../../common/.config/brew/Brewfile.optional", brewfile_dir),
].find { |path| File.file?(path) }

abort("Brewfile.core not found") unless core_brewfile

instance_eval(File.read(core_brewfile))
instance_eval(File.read(common_optional_brewfile)) if common_optional_brewfile
